### ISSUE TITLE
wrong abbreviation in infrastructure.md

### ISSUE THREAD

**Issue by DavidFichtmueller** [tdwg/charters#4]
In charters/infrastructure.md at line 5 the abbreviation FC is used: "The purpose of the Infrastructure Functional Subcommittee (FC) [...]", throughout the rest of the text however the Functional Subcommittee is referred to as FS. So the FC from the introduction should be changed to FS.

**Comment by peterdesmet** [comment]
Thanks! Corrected, should be live once #5 is accepted.
